#!/bin/bash
#SBATCH --job-name=cactus_turtle_mask_test
#SBATCH --output=%x-%j.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=gthomas@g.harvard.edu
#SBATCH --partition=gpu_test
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=24
#SBATCH --mem=100g
#SBATCH --time=1:00:00
#SBATCH --gpus=4
#SBATCH --gres=gpu:4
#SBATCH --gpu-freq=high

TMPDIR=/n/holylfs05/LABS/informatics/Users/gthomas/tmp/

cd /n/holylfs05/LABS/informatics/Users/gthomas/turtles/cactus/

## generated by : /usr/local/bin/cactus-prepare genomes.txt --outDir turtle-output --outSeqFile turtle-output/turtles.txt --outHal turtle-output/turtles.hal --jobStore jobstore --gpu --defaultCores 32
## date : 2022-03-24 18:52:28.444716
## cactus commit : f1eef4024bc70da92e1d269028613f16ec1a774b


## Preprocessor
#time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif cactus-preprocess jobstore/0 genomes.txt turtle-output/turtles.txt --inputNames Pmegacephalum Cmccordii Cabingdonii --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --maxCores 64 --gpu
#time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif cactus-preprocess jobstore/1 genomes.txt turtle-output/turtles.txt --inputNames Gevgoodei Amarmorata Cinsculpta --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --maxCores 64 --gpu
#time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif cactus-preprocess jobstore/2 genomes.txt turtle-output/turtles.txt --inputNames Esubglobosa Mtuberculata Pcastaneus --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --maxCores 64 --gpu
#time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif cactus-preprocess jobstore/3 genomes.txt turtle-output/turtles.txt --inputNames Pexpansa Mmutica Mreevesii --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --maxCores 64 --gpu
#time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif cactus-preprocess jobstore/4 genomes.txt turtle-output/turtles.txt --inputNames Cpicta Dmawii Cserpentina --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --maxCores 64 --gpu
#time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif cactus-preprocess jobstore/5 genomes.txt turtle-output/turtles.txt --inputNames Dcoriacea Psinensis Rswinhoei --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --maxCores 64 --gpu
#time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif cactus-preprocess jobstore/6 genomes.txt turtle-output/turtles.txt --inputNames Tscripta Mterrapin Cinsculpta --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --maxCores 64 --gpu
time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif cactus-preprocess jobstore/7 genomes.txt turtle-output/turtles.txt --inputNames Cmydas --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --maxCores 24 --defaultCores 24 --gpu
## 3:20 with 100g and 64cpu and 4gpu

## Alignment

### Round 0
# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif cactus-blast jobstore/8 turtle-output/turtles.txt turtle-output/Anc08.cigar --root Anc08 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --maxCores 64 --gpu --restart
## 11:33 with a full gpu node (64cpu, 4gpu, no mem limit)

#time -p singularity exec --nv --cleanenv --bind ${TMPDIR}:/tmp cactus_v2.0.5-gpu.sif cactus-align jobstore/9 turtle-output/turtles.txt turtle-output/Anc08.cigar turtle-output/Anc08.hal --root Anc08 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --maxCores 64 --realTimeLogging
## 13:27 with 1tb and 36cpu (holy-cow)
## 10:38 with 400gb and 64cpu (bigmem)

#time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif hal2fasta turtle-output/Anc08.hal Anc08 --hdf5InMemory > turtle-output/Anc08.fa
## 30 seconds with 100gb and 48 cpu (shared)

# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif cactus-blast jobstore/10 turtle-output/turtles.txt turtle-output/Anc12.cigar --root Anc12 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --maxCores 32 --gpu
# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif cactus-align jobstore/11 turtle-output/turtles.txt turtle-output/Anc12.cigar turtle-output/Anc12.hal --root Anc12 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --maxCores 32
# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif hal2fasta turtle-output/Anc12.hal Anc12 --hdf5InMemory > turtle-output/Anc12.fa

# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif cactus-blast jobstore/12 turtle-output/turtles.txt turtle-output/Anc13.cigar --root Anc13 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --maxCores 32 --gpu
# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif cactus-align jobstore/13 turtle-output/turtles.txt turtle-output/Anc13.cigar turtle-output/Anc13.hal --root Anc13 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --maxCores 32
# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif hal2fasta turtle-output/Anc13.hal Anc13 --hdf5InMemory > turtle-output/Anc13.fa

# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif cactus-blast jobstore/14 turtle-output/turtles.txt turtle-output/Anc14.cigar --root Anc14 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --maxCores 32 --gpu
# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif cactus-align jobstore/15 turtle-output/turtles.txt turtle-output/Anc14.cigar turtle-output/Anc14.hal --root Anc14 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --maxCores 32
# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif hal2fasta turtle-output/Anc14.hal Anc14 --hdf5InMemory > turtle-output/Anc14.fa

# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif cactus-blast jobstore/16 turtle-output/turtles.txt turtle-output/Anc16.cigar --root Anc16 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --maxCores 32 --gpu
# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif cactus-align jobstore/17 turtle-output/turtles.txt turtle-output/Anc16.cigar turtle-output/Anc16.hal --root Anc16 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --maxCores 32
# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif hal2fasta turtle-output/Anc16.hal Anc16 --hdf5InMemory > turtle-output/Anc16.fa

# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif cactus-blast jobstore/18 turtle-output/turtles.txt turtle-output/Anc18.cigar --root Anc18 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --maxCores 32 --gpu
# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif cactus-align jobstore/19 turtle-output/turtles.txt turtle-output/Anc18.cigar turtle-output/Anc18.hal --root Anc18 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --maxCores 32
# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif hal2fasta turtle-output/Anc18.hal Anc18 --hdf5InMemory > turtle-output/Anc18.fa

# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif cactus-blast jobstore/20 turtle-output/turtles.txt turtle-output/Anc19.cigar --root Anc19 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --maxCores 32 --gpu
# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif cactus-align jobstore/21 turtle-output/turtles.txt turtle-output/Anc19.cigar turtle-output/Anc19.hal --root Anc19 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --maxCores 32
# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif hal2fasta turtle-output/Anc19.hal Anc19 --hdf5InMemory > turtle-output/Anc19.fa

# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif cactus-blast jobstore/22 turtle-output/turtles.txt turtle-output/Anc20.cigar --root Anc20 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --maxCores 32 --gpu
# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif cactus-align jobstore/23 turtle-output/turtles.txt turtle-output/Anc20.cigar turtle-output/Anc20.hal --root Anc20 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --maxCores 32
# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif hal2fasta turtle-output/Anc20.hal Anc20 --hdf5InMemory > turtle-output/Anc20.fa

### Round 1
# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif cactus-blast jobstore/24 turtle-output/turtles.txt turtle-output/Anc06.cigar --root Anc06 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --maxCores 32 --gpu
# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif cactus-align jobstore/25 turtle-output/turtles.txt turtle-output/Anc06.cigar turtle-output/Anc06.hal --root Anc06 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --maxCores 32
# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif hal2fasta turtle-output/Anc06.hal Anc06 --hdf5InMemory > turtle-output/Anc06.fa

# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif cactus-blast jobstore/26 turtle-output/turtles.txt turtle-output/Anc07.cigar --root Anc07 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --maxCores 32
# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif cactus-align jobstore/27 turtle-output/turtles.txt turtle-output/Anc07.cigar turtle-output/Anc07.hal --root Anc07 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --maxCores 32
# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif hal2fasta turtle-output/Anc07.hal Anc07 --hdf5InMemory > turtle-output/Anc07.fa

# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif cactus-blast jobstore/28 turtle-output/turtles.txt turtle-output/Anc11.cigar --root Anc11 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --maxCores 32 --gpu
# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif cactus-align jobstore/29 turtle-output/turtles.txt turtle-output/Anc11.cigar turtle-output/Anc11.hal --root Anc11 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --maxCores 32
# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif hal2fasta turtle-output/Anc11.hal Anc11 --hdf5InMemory > turtle-output/Anc11.fa

# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif cactus-blast jobstore/30 turtle-output/turtles.txt turtle-output/Anc15.cigar --root Anc15 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --maxCores 32 --gpu
# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif cactus-align jobstore/31 turtle-output/turtles.txt turtle-output/Anc15.cigar turtle-output/Anc15.hal --root Anc15 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --maxCores 32
# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif hal2fasta turtle-output/Anc15.hal Anc15 --hdf5InMemory > turtle-output/Anc15.fa

# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif cactus-blast jobstore/32 turtle-output/turtles.txt turtle-output/Anc17.cigar --root Anc17 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --maxCores 32 --gpu
# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif cactus-align jobstore/33 turtle-output/turtles.txt turtle-output/Anc17.cigar turtle-output/Anc17.hal --root Anc17 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --maxCores 32
# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif hal2fasta turtle-output/Anc17.hal Anc17 --hdf5InMemory > turtle-output/Anc17.fa

### Round 2
# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif cactus-blast jobstore/34 turtle-output/turtles.txt turtle-output/Anc03.cigar --root Anc03 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --maxCores 32 --gpu
# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif cactus-align jobstore/35 turtle-output/turtles.txt turtle-output/Anc03.cigar turtle-output/Anc03.hal --root Anc03 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --maxCores 32
# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif hal2fasta turtle-output/Anc03.hal Anc03 --hdf5InMemory > turtle-output/Anc03.fa

# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif cactus-blast jobstore/36 turtle-output/turtles.txt turtle-output/Anc09.cigar --root Anc09 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --maxCores 32 --gpu
# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif cactus-align jobstore/37 turtle-output/turtles.txt turtle-output/Anc09.cigar turtle-output/Anc09.hal --root Anc09 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --maxCores 32
# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif hal2fasta turtle-output/Anc09.hal Anc09 --hdf5InMemory > turtle-output/Anc09.fa

# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif cactus-blast jobstore/38 turtle-output/turtles.txt turtle-output/Anc10.cigar --root Anc10 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --maxCores 32 --gpu
# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif cactus-align jobstore/39 turtle-output/turtles.txt turtle-output/Anc10.cigar turtle-output/Anc10.hal --root Anc10 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --maxCores 32
# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif hal2fasta turtle-output/Anc10.hal Anc10 --hdf5InMemory > turtle-output/Anc10.fa

### Round 3
# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif cactus-blast jobstore/40 turtle-output/turtles.txt turtle-output/Anc04.cigar --root Anc04 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --maxCores 32 --gpu
# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif cactus-align jobstore/41 turtle-output/turtles.txt turtle-output/Anc04.cigar turtle-output/Anc04.hal --root Anc04 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --maxCores 32
# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif hal2fasta turtle-output/Anc04.hal Anc04 --hdf5InMemory > turtle-output/Anc04.fa

# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif cactus-blast jobstore/42 turtle-output/turtles.txt turtle-output/Anc05.cigar --root Anc05 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --maxCores 32 --gpu
# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif cactus-align jobstore/43 turtle-output/turtles.txt turtle-output/Anc05.cigar turtle-output/Anc05.hal --root Anc05 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --maxCores 32
# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif hal2fasta turtle-output/Anc05.hal Anc05 --hdf5InMemory > turtle-output/Anc05.fa

### Round 4
# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif cactus-blast jobstore/44 turtle-output/turtles.txt turtle-output/Anc01.cigar --root Anc01 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --maxCores 32 --gpu
# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif cactus-align jobstore/45 turtle-output/turtles.txt turtle-output/Anc01.cigar turtle-output/Anc01.hal --root Anc01 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --maxCores 32
# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif hal2fasta turtle-output/Anc01.hal Anc01 --hdf5InMemory > turtle-output/Anc01.fa

# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif cactus-blast jobstore/46 turtle-output/turtles.txt turtle-output/Anc02.cigar --root Anc02 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --maxCores 32 --gpu
# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif cactus-align jobstore/47 turtle-output/turtles.txt turtle-output/Anc02.cigar turtle-output/Anc02.hal --root Anc02 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --maxCores 32
# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif hal2fasta turtle-output/Anc02.hal Anc02 --hdf5InMemory > turtle-output/Anc02.fa

### Round 5
# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif cactus-blast jobstore/48 turtle-output/turtles.txt turtle-output/Anc00.cigar --root Anc00 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --maxCores 32 --gpu
# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif cactus-align jobstore/49 turtle-output/turtles.txt turtle-output/Anc00.cigar turtle-output/turtles.hal --root Anc00 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --maxCores 32
# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif hal2fasta turtle-output/turtles.hal Anc00 --hdf5InMemory > turtle-output/Anc00.fa

## HAL merging
# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif halAppendSubtree turtle-output/turtles.hal turtle-output/Anc01.hal Anc01 Anc01 --merge --hdf5InMemory
# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif halAppendSubtree turtle-output/turtles.hal turtle-output/Anc02.hal Anc02 Anc02 --merge --hdf5InMemory
# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif halAppendSubtree turtle-output/turtles.hal turtle-output/Anc04.hal Anc04 Anc04 --merge --hdf5InMemory
# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif halAppendSubtree turtle-output/turtles.hal turtle-output/Anc05.hal Anc05 Anc05 --merge --hdf5InMemory
# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif halAppendSubtree turtle-output/turtles.hal turtle-output/Anc03.hal Anc03 Anc03 --merge --hdf5InMemory
# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif halAppendSubtree turtle-output/turtles.hal turtle-output/Anc09.hal Anc09 Anc09 --merge --hdf5InMemory
# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif halAppendSubtree turtle-output/turtles.hal turtle-output/Anc10.hal Anc10 Anc10 --merge --hdf5InMemory
# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif halAppendSubtree turtle-output/turtles.hal turtle-output/Anc06.hal Anc06 Anc06 --merge --hdf5InMemory
# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif halAppendSubtree turtle-output/turtles.hal turtle-output/Anc07.hal Anc07 Anc07 --merge --hdf5InMemory
# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif halAppendSubtree turtle-output/turtles.hal turtle-output/Anc11.hal Anc11 Anc11 --merge --hdf5InMemory
# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif halAppendSubtree turtle-output/turtles.hal turtle-output/Anc15.hal Anc15 Anc15 --merge --hdf5InMemory
# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif halAppendSubtree turtle-output/turtles.hal turtle-output/Anc17.hal Anc17 Anc17 --merge --hdf5InMemory
# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif halAppendSubtree turtle-output/turtles.hal turtle-output/Anc08.hal Anc08 Anc08 --merge --hdf5InMemory
# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif halAppendSubtree turtle-output/turtles.hal turtle-output/Anc12.hal Anc12 Anc12 --merge --hdf5InMemory
# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif halAppendSubtree turtle-output/turtles.hal turtle-output/Anc13.hal Anc13 Anc13 --merge --hdf5InMemory
# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif halAppendSubtree turtle-output/turtles.hal turtle-output/Anc14.hal Anc14 Anc14 --merge --hdf5InMemory
# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif halAppendSubtree turtle-output/turtles.hal turtle-output/Anc16.hal Anc16 Anc16 --merge --hdf5InMemory
# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif halAppendSubtree turtle-output/turtles.hal turtle-output/Anc18.hal Anc18 Anc18 --merge --hdf5InMemory
# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif halAppendSubtree turtle-output/turtles.hal turtle-output/Anc19.hal Anc19 Anc19 --merge --hdf5InMemory
# time -p singularity exec --nv --cleanenv cactus_v2.0.5-gpu.sif halAppendSubtree turtle-output/turtles.hal turtle-output/Anc20.hal Anc20 Anc20 --merge --hdf5InMemory
































## generated by : /usr/local/bin/cactus-prepare genomes.txt --outDir turtle-output --outSeqFile turtle-output/turtles.txt --outHal turtle-output/turtles.hal --jobStore jobstore --gpu
## date : 2022-01-21 23:33:35.515452
## cactus commit : eca7219f3943465b73f240dd86b5e8e228162144

## Preprocessor
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif cactus-preprocess --defaultCores=${SLURM_CPUS_ON_NODE} jobstore/0 genomes.txt turtle-output/turtles.txt --inputNames Pmegacephalum Cmccordii Cabingdonii --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --gpu
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif cactus-preprocess --defaultCores=${SLURM_CPUS_ON_NODE} jobstore/1 genomes.txt turtle-output/turtles.txt --inputNames Gevgoodei Amarmorata Cinsculpta --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --gpu
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif cactus-preprocess --defaultCores=${SLURM_CPUS_ON_NODE} jobstore/2 genomes.txt turtle-output/turtles.txt --inputNames Esubglobosa Mtuberculata Pcastaneus --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --gpu
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif cactus-preprocess --defaultCores=${SLURM_CPUS_ON_NODE} jobstore/3 genomes.txt turtle-output/turtles.txt --inputNames Pexpansa Mmutica Mreevesii --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --gpu
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif cactus-preprocess --defaultCores=${SLURM_CPUS_ON_NODE} jobstore/4 genomes.txt turtle-output/turtles.txt --inputNames Cpicta Dmawii Cserpentina --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --gpu
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif cactus-preprocess --defaultCores=${SLURM_CPUS_ON_NODE} jobstore/5 genomes.txt turtle-output/turtles.txt --inputNames Dcoriacea Psinensis Rswinhoei --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --gpu
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif cactus-preprocess --defaultCores=${SLURM_CPUS_ON_NODE} jobstore/6 genomes.txt turtle-output/turtles.txt --inputNames Tscripta Mterrapin Cmydas --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --gpu
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif cactus-preprocess --defaultCores=${SLURM_CPUS_ON_NODE} jobstore/7 genomes.txt turtle-output/turtles.txt --inputNames Lkempii --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --gpu

## Alignment

### Round 0
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif cactus-blast --defaultCores=${SLURM_CPUS_ON_NODE} jobstore/8 turtle-output/turtles.txt turtle-output/Anc08.cigar --root Anc08 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --gpu
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif cactus-align --defaultCores=${SLURM_CPUS_ON_NODE} jobstore/9 turtle-output/turtles.txt turtle-output/Anc08.cigar turtle-output/Anc08.hal --root Anc08 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --maxCores ${SLURM_CPUS_ON_NODE}
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif hal2fasta turtle-output/Anc08.hal Anc08 --hdf5InMemory > turtle-output/Anc08.fa

# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif cactus-blast --defaultCores=${SLURM_CPUS_ON_NODE} jobstore/10 turtle-output/turtles.txt turtle-output/Anc12.cigar --root Anc12 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --gpu
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif cactus-align --defaultCores=${SLURM_CPUS_ON_NODE} jobstore/11 turtle-output/turtles.txt turtle-output/Anc12.cigar turtle-output/Anc12.hal --root Anc12 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --maxCores ${SLURM_CPUS_ON_NODE} 
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif hal2fasta turtle-output/Anc12.hal Anc12 --hdf5InMemory > turtle-output/Anc12.fa

# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif cactus-blast --defaultCores=${SLURM_CPUS_ON_NODE} jobstore/12 turtle-output/turtles.txt turtle-output/Anc13.cigar --root Anc13 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --gpu
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif cactus-align --defaultCores=${SLURM_CPUS_ON_NODE} jobstore/13 turtle-output/turtles.txt turtle-output/Anc13.cigar turtle-output/Anc13.hal --root Anc13 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --maxCores ${SLURM_CPUS_ON_NODE} 
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif hal2fasta turtle-output/Anc13.hal Anc13 --hdf5InMemory > turtle-output/Anc13.fa

# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif cactus-blast --defaultCores=${SLURM_CPUS_ON_NODE} --defaultCores=${SLURM_CPUS_ON_NODE} jobstore/14 turtle-output/turtles.txt turtle-output/Anc14.cigar --root Anc14 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --gpu
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif cactus-align --defaultCores=${SLURM_CPUS_ON_NODE} --defaultCores=${SLURM_CPUS_ON_NODE} jobstore/15 turtle-output/turtles.txt turtle-output/Anc14.cigar turtle-output/Anc14.hal --root Anc14 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --maxCores ${SLURM_CPUS_ON_NODE} 
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif hal2fasta turtle-output/Anc14.hal Anc14 --hdf5InMemory > turtle-output/Anc14.fa

# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif cactus-blast --defaultCores=${SLURM_CPUS_ON_NODE} jobstore/16 turtle-output/turtles.txt turtle-output/Anc16.cigar --root Anc16 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --gpu
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif cactus-align --defaultCores=${SLURM_CPUS_ON_NODE} jobstore/17 turtle-output/turtles.txt turtle-output/Anc16.cigar turtle-output/Anc16.hal --root Anc16 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --maxCores ${SLURM_CPUS_ON_NODE} 
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif hal2fasta turtle-output/Anc16.hal Anc16 --hdf5InMemory > turtle-output/Anc16.fa

# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif cactus-blast --defaultCores=${SLURM_CPUS_ON_NODE} jobstore/18 turtle-output/turtles.txt turtle-output/Anc18.cigar --root Anc18 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --gpu
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif cactus-align --defaultCores=${SLURM_CPUS_ON_NODE} jobstore/19 turtle-output/turtles.txt turtle-output/Anc18.cigar turtle-output/Anc18.hal --root Anc18 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --maxCores ${SLURM_CPUS_ON_NODE} 
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif hal2fasta turtle-output/Anc18.hal Anc18 --hdf5InMemory > turtle-output/Anc18.fa

# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif cactus-blast --defaultCores=${SLURM_CPUS_ON_NODE} jobstore/20 turtle-output/turtles.txt turtle-output/Anc19.cigar --root Anc19 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --gpu
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif cactus-align --defaultCores=${SLURM_CPUS_ON_NODE} jobstore/21 turtle-output/turtles.txt turtle-output/Anc19.cigar turtle-output/Anc19.hal --root Anc19 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --maxCores ${SLURM_CPUS_ON_NODE} 
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif hal2fasta turtle-output/Anc19.hal Anc19 --hdf5InMemory > turtle-output/Anc19.fa

# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif cactus-blast --defaultCores=${SLURM_CPUS_ON_NODE} jobstore/22 turtle-output/turtles.txt turtle-output/Anc20.cigar --root Anc20 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --gpu
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif cactus-align --defaultCores=${SLURM_CPUS_ON_NODE} jobstore/23 turtle-output/turtles.txt turtle-output/Anc20.cigar turtle-output/Anc20.hal --root Anc20 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --maxCores ${SLURM_CPUS_ON_NODE} 
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif hal2fasta turtle-output/Anc20.hal Anc20 --hdf5InMemory > turtle-output/Anc20.fa

### Round 1
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif cactus-blast --defaultCores=${SLURM_CPUS_ON_NODE} jobstore/24 turtle-output/turtles.txt turtle-output/Anc06.cigar --root Anc06 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --gpu
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif cactus-align --defaultCores=${SLURM_CPUS_ON_NODE} jobstore/25 turtle-output/turtles.txt turtle-output/Anc06.cigar turtle-output/Anc06.hal --root Anc06 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --maxCores ${SLURM_CPUS_ON_NODE} 
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif hal2fasta turtle-output/Anc06.hal Anc06 --hdf5InMemory > turtle-output/Anc06.fa

# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif cactus-blast --defaultCores=${SLURM_CPUS_ON_NODE} jobstore/26 turtle-output/turtles.txt turtle-output/Anc07.cigar --root Anc07 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --gpu
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif cactus-align --defaultCores=${SLURM_CPUS_ON_NODE} jobstore/27 turtle-output/turtles.txt turtle-output/Anc07.cigar turtle-output/Anc07.hal --root Anc07 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --maxCores ${SLURM_CPUS_ON_NODE} 
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif hal2fasta turtle-output/Anc07.hal Anc07 --hdf5InMemory > turtle-output/Anc07.fa

# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif cactus-blast --defaultCores=${SLURM_CPUS_ON_NODE} jobstore/28 turtle-output/turtles.txt turtle-output/Anc11.cigar --root Anc11 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --gpu
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif cactus-align --defaultCores=${SLURM_CPUS_ON_NODE} jobstore/29 turtle-output/turtles.txt turtle-output/Anc11.cigar turtle-output/Anc11.hal --root Anc11 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --maxCores ${SLURM_CPUS_ON_NODE}
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif hal2fasta turtle-output/Anc11.hal Anc11 --hdf5InMemory > turtle-output/Anc11.fa

# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif cactus-blast --defaultCores=${SLURM_CPUS_ON_NODE} jobstore/30 turtle-output/turtles.txt turtle-output/Anc15.cigar --root Anc15 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --gpu
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif cactus-align --defaultCores=${SLURM_CPUS_ON_NODE} jobstore/31 turtle-output/turtles.txt turtle-output/Anc15.cigar turtle-output/Anc15.hal --root Anc15 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --maxCores ${SLURM_CPUS_ON_NODE} 
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif hal2fasta turtle-output/Anc15.hal Anc15 --hdf5InMemory > turtle-output/Anc15.fa

# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif cactus-blast --defaultCores=${SLURM_CPUS_ON_NODE} jobstore/32 turtle-output/turtles.txt turtle-output/Anc17.cigar --root Anc17 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --gpu
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif cactus-align --defaultCores=${SLURM_CPUS_ON_NODE} jobstore/33 turtle-output/turtles.txt turtle-output/Anc17.cigar turtle-output/Anc17.hal --root Anc17 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --maxCores ${SLURM_CPUS_ON_NODE} 
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif hal2fasta turtle-output/Anc17.hal Anc17 --hdf5InMemory > turtle-output/Anc17.fa

### Round 2
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif cactus-blast --defaultCores=${SLURM_CPUS_ON_NODE} jobstore/34 turtle-output/turtles.txt turtle-output/Anc03.cigar --root Anc03 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --gpu
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif cactus-align --defaultCores=${SLURM_CPUS_ON_NODE} jobstore/35 turtle-output/turtles.txt turtle-output/Anc03.cigar turtle-output/Anc03.hal --root Anc03 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --maxCores ${SLURM_CPUS_ON_NODE} 
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif hal2fasta turtle-output/Anc03.hal Anc03 --hdf5InMemory > turtle-output/Anc03.fa

# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif cactus-blast --defaultCores=${SLURM_CPUS_ON_NODE} jobstore/36 turtle-output/turtles.txt turtle-output/Anc09.cigar --root Anc09 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --gpu
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif cactus-align --defaultCores=${SLURM_CPUS_ON_NODE} jobstore/37 turtle-output/turtles.txt turtle-output/Anc09.cigar turtle-output/Anc09.hal --root Anc09 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --maxCores ${SLURM_CPUS_ON_NODE} 
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif hal2fasta turtle-output/Anc09.hal Anc09 --hdf5InMemory > turtle-output/Anc09.fa

# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif cactus-blast --defaultCores=${SLURM_CPUS_ON_NODE} jobstore/38 turtle-output/turtles.txt turtle-output/Anc10.cigar --root Anc10 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --gpu
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif cactus-align --defaultCores=${SLURM_CPUS_ON_NODE} jobstore/39 turtle-output/turtles.txt turtle-output/Anc10.cigar turtle-output/Anc10.hal --root Anc10 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --maxCores ${SLURM_CPUS_ON_NODE} 
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif hal2fasta turtle-output/Anc10.hal Anc10 --hdf5InMemory > turtle-output/Anc10.fa

### Round 3
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif cactus-blast --defaultCores=${SLURM_CPUS_ON_NODE} jobstore/40 turtle-output/turtles.txt turtle-output/Anc04.cigar --root Anc04 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --gpu
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif cactus-align --defaultCores=${SLURM_CPUS_ON_NODE} jobstore/41 turtle-output/turtles.txt turtle-output/Anc04.cigar turtle-output/Anc04.hal --root Anc04 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --maxCores ${SLURM_CPUS_ON_NODE} 
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif hal2fasta turtle-output/Anc04.hal Anc04 --hdf5InMemory > turtle-output/Anc04.fa

# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif cactus-blast --defaultCores=${SLURM_CPUS_ON_NODE} jobstore/42 turtle-output/turtles.txt turtle-output/Anc05.cigar --root Anc05 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --gpu
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif cactus-align --defaultCores=${SLURM_CPUS_ON_NODE} jobstore/43 turtle-output/turtles.txt turtle-output/Anc05.cigar turtle-output/Anc05.hal --root Anc05 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --maxCores ${SLURM_CPUS_ON_NODE} 
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif hal2fasta turtle-output/Anc05.hal Anc05 --hdf5InMemory > turtle-output/Anc05.fa

### Round 4
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif cactus-blast --defaultCores=${SLURM_CPUS_ON_NODE} jobstore/44 turtle-output/turtles.txt turtle-output/Anc01.cigar --root Anc01 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --gpu
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif cactus-align --defaultCores=${SLURM_CPUS_ON_NODE} jobstore/45 turtle-output/turtles.txt turtle-output/Anc01.cigar turtle-output/Anc01.hal --root Anc01 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --maxCores ${SLURM_CPUS_ON_NODE} 
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif hal2fasta turtle-output/Anc01.hal Anc01 --hdf5InMemory > turtle-output/Anc01.fa

# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif cactus-blast --defaultCores=${SLURM_CPUS_ON_NODE} jobstore/46 turtle-output/turtles.txt turtle-output/Anc02.cigar --root Anc02 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --gpu
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif cactus-align --defaultCores=${SLURM_CPUS_ON_NODE} jobstore/47 turtle-output/turtles.txt turtle-output/Anc02.cigar turtle-output/Anc02.hal --root Anc02 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --maxCores ${SLURM_CPUS_ON_NODE} 
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif hal2fasta turtle-output/Anc02.hal Anc02 --hdf5InMemory > turtle-output/Anc02.fa

### Round 5
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif cactus-blast --defaultCores=${SLURM_CPUS_ON_NODE} jobstore/48 turtle-output/turtles.txt turtle-output/Anc00.cigar --root Anc00 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --gpu
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif cactus-align --defaultCores=${SLURM_CPUS_ON_NODE} jobstore/49 turtle-output/turtles.txt turtle-output/Anc00.cigar turtle-output/turtles.hal --root Anc00 --realTimeLogging --logInfo --retryCount 0 --configFile turtle-output/config-prepared.xml --maxCores ${SLURM_CPUS_ON_NODE} 
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif hal2fasta turtle-output/turtles.hal Anc00 --hdf5InMemory > turtle-output/Anc00.fa

## HAL merging
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif halAppendSubtree turtle-output/turtles.hal turtle-output/Anc01.hal Anc01 Anc01 --merge --hdf5InMemory
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif halAppendSubtree turtle-output/turtles.hal turtle-output/Anc02.hal Anc02 Anc02 --merge --hdf5InMemory
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif halAppendSubtree turtle-output/turtles.hal turtle-output/Anc05.hal Anc05 Anc05 --merge --hdf5InMemory
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif halAppendSubtree turtle-output/turtles.hal turtle-output/Anc04.hal Anc04 Anc04 --merge --hdf5InMemory
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif halAppendSubtree turtle-output/turtles.hal turtle-output/Anc03.hal Anc03 Anc03 --merge --hdf5InMemory
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif halAppendSubtree turtle-output/turtles.hal turtle-output/Anc10.hal Anc10 Anc10 --merge --hdf5InMemory
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif halAppendSubtree turtle-output/turtles.hal turtle-output/Anc09.hal Anc09 Anc09 --merge --hdf5InMemory
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif halAppendSubtree turtle-output/turtles.hal turtle-output/Anc07.hal Anc07 Anc07 --merge --hdf5InMemory
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif halAppendSubtree turtle-output/turtles.hal turtle-output/Anc17.hal Anc17 Anc17 --merge --hdf5InMemory
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif halAppendSubtree turtle-output/turtles.hal turtle-output/Anc15.hal Anc15 Anc15 --merge --hdf5InMemory
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif halAppendSubtree turtle-output/turtles.hal turtle-output/Anc06.hal Anc06 Anc06 --merge --hdf5InMemory
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif halAppendSubtree turtle-output/turtles.hal turtle-output/Anc11.hal Anc11 Anc11 --merge --hdf5InMemory
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif halAppendSubtree turtle-output/turtles.hal turtle-output/Anc13.hal Anc13 Anc13 --merge --hdf5InMemory
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif halAppendSubtree turtle-output/turtles.hal turtle-output/Anc18.hal Anc18 Anc18 --merge --hdf5InMemory
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif halAppendSubtree turtle-output/turtles.hal turtle-output/Anc14.hal Anc14 Anc14 --merge --hdf5InMemory
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif halAppendSubtree turtle-output/turtles.hal turtle-output/Anc16.hal Anc16 Anc16 --merge --hdf5InMemory
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif halAppendSubtree turtle-output/turtles.hal turtle-output/Anc12.hal Anc12 Anc12 --merge --hdf5InMemory
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif halAppendSubtree turtle-output/turtles.hal turtle-output/Anc08.hal Anc08 Anc08 --merge --hdf5InMemory
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif halAppendSubtree turtle-output/turtles.hal turtle-output/Anc20.hal Anc20 Anc20 --merge --hdf5InMemory
# time -p singularity exec --nv --cleanenv cactus_v2.0.4-gpu.sif halAppendSubtree turtle-output/turtles.hal turtle-output/Anc19.hal Anc19 Anc19 --merge --hdf5InMemory

